### ISSUE TITLE
Make sure adding a new file to site's content tree triggers hmr

### ISSUE THREAD

**Issue by andreypopp** [andreypopp/sitegen#16]

**Comment by KyleAMathews** [comment]
I couldn't figure out how to make this work... so please teach me if you do :) https://github.com/webpack/webpack/issues/1162

**Comment by andreypopp** [comment]
Works for me, closing. `this.addContextDependency(directory)` is what I use now (because I need much more sophisticated filtering than `require.context`). cc @KyleAMathews
