### ISSUE TITLE
so...is project dead?!

### ISSUE THREAD

**Issue by plandem** [andreypopp/sitegen#22]

**Comment by andreypopp** [comment]
Unfortunately I don't have time to work on it right now :( gatsby is what I've heard good things about

**Comment by plandem** [comment]
I see. It's sad, because this one looks like more simple in use.

**Comment by andreypopp** [comment]
Right, the concept is sane and simple, and I wish somebody could implement
it better than me.

**Comment by plandem** [comment]
Do you use gatsby(so we have no chance for reanimating) or sitegen(we have some chances for reanimation) by yourself?!

**Comment by andreypopp** [comment]
Neither of those right now.

**Comment by plandem** [comment]
no need or dropped the idea/concept?

P.S.: just started to research this direction and your solution and https://github.com/jakedeichert/rovr - only that looks like not overwhelming

**Comment by andreypopp** [comment]
No need.

Thanks for link to rovr, I'll take a look.

I have another API sketch for static site generator based on React — see [site config](https://github.com/andreypopp/datom/blob/master/site/site.js) and [page component](https://github.com/andreypopp/datom/blob/master/site/index.js) as examples — but that's just sketch (no implementation).

**Comment by plandem** [comment]
So...do you start to work on a new generator? :) I see it based on GraphQL - gatsby took same route recently.

**Comment by plandem** [comment]
maybe this one will be interesting for you: https://github.com/alizain/fsdb

got this link at gatsby's [issue](https://tinyurl.com/lyze2wn)

**Comment by andreypopp** [comment]
Well, not really working on it right now but just had an idea of GraphQL query to webpack compiler which can be used to query data for a static site generator.

The main idea in sitegen (apart from simple API) is that pages can be React components, not just static markdown (or whatever) files. That's the important thing as it allows to build any kind of sites — doc sites, interactive sites and so on.

**Comment by plandem** [comment]
it's a great pity, but I can't make your sitegen to work :(

**Comment by plandem** [comment]
btw, maybe it will be interesting for you:
https://github.com/plandem/rrrouter

and some provider implementations:
https://github.com/plandem/rrrouter-provider-history
https://github.com/plandem/rrrouter-provider-redux
